# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52d82563b880628803b18d2d46fa5e9a2c87134c178a971d04d02aaeca548c62af6ad12df269d776eebc042793450390c28a32fbac713523790a360814904cb9

test:
  secret_key_base: b2f2231af66a5e9025da533e73ca3fe9f666a155cf866c5af914dfff854e32be91b52105ccf902f68c892169140e32cb304f6b18878cda3e0e724e14af415de9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
